[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    "dia-batching-server",
    'pallets/dia-oracle',
    'pallets/dia-oracle/rpc',
    'pallets/dia-oracle/rpc/runtime-api',
    'runtime',
]
